import type { JobState } from '../state'
import type * as JobTypes from '../../../jobTypes'
export function createJobSummary(
  partial: Partial<JobTypes.JobSummary> = {}
): JobTypes.JobSummary {
  return {
    active_node_key: null,
    batch_id: '',
    completed_nodes: 0,
    created_at: '',
    error_message: '',
    error_summary: '',
    id: '',
    node_summaries: undefined,
    source_id: '',
    source_type: '',
    status: '',
    storage_dir: '',
    title: '',
    total_nodes: 0,
    updated_at: '',
    workflow_key: '',
    workspace_id: '',
    workflow_revision_id: '',
    workflow_version: null,
    workflow_definition_hash: '',
    outcome: '',
    current_workflow_revision_id: '',
    current_workflow_revision_version: null,
    is_workflow_outdated: false,
    packed: 0,
    ...partial,
  }
}
export function createJobState(partial: Partial<JobState> = {}): JobState {
  return {
    jobs: [],
    jobsWorkspaceId: null,
    isLoading: false,
    error: null,
    selectedIds: new Set(),
    expandedId: null,
    filterConfig: {
      status: null,
      search: '',
      workflowVersion: null,
      activeNodeKey: null,
    },
    selectMode: false,
    batchDeleteLoading: false,
    batchPackageLoading: false,
    batchRerunLoading: false,
    batchRunToLoading: false,
    continueLoading: false,
    batchUpgradeWorkflowLoading: false,
    fetchJobs: async () => {},
    setJobsAndFinishLoading: () => {},
    resetForWorkspace: () => {},
    failJobFetch: () => {},
    setFilterConfig: () => {},
    toggleSelectMode: () => {},
    toggleSelect: () => {},
    selectAll: () => {},
    selectFailed: () => {},
    selectUnpacked: () => {},
    clearSelection: () => {},
    toggleExpand: () => {},
    getFilteredJobs: () => [],
    batchRerun: async () => ({ results: [] }),
    batchDelete: async () => ({ results: [] }),
    batchPackage: async () => ({
      failed_count: 0,
      results: [],
      succeeded_count: 0,
    }),
    batchRunTo: async () => ({ results: [] }),
    batchUpgradeWorkflow: async () => ({ results: [] }),
    continueJob: async () => ({
      job_id: '',
      operation: '',
      status: '',
    }),
    ...partial,
  }
}
