create table if not exists videos (
  id text primary key,
  source_url text not null,
  title text not null,
  storage_dir text not null default '',
  current_phase text not null default 'download',
  status text not null default 'queued',
  duration double precision not null default 0,
  error_message text not null default '',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  content_type text not null default 'knowledge',
  external_id text not null default '',
  knowledge_code text not null default '',
  question_id text not null default '',
  source_uuid text not null default '',
  packed integer not null default 0,
  interaction_stats_json text not null default '',
  interaction_review_status text not null default ''
);

create table if not exists phase_runs (
  id bigint generated by default as identity primary key,
  video_id text not null references videos(id) on delete cascade,
  phase_key text not null,
  status text not null,
  started_at timestamptz not null default current_timestamp,
  finished_at timestamptz,
  command_json text not null default '[]',
  exit_code integer,
  log_path text not null default '',
  error_message text not null default ''
);

create table if not exists transcription_runs (
  id bigint generated by default as identity primary key,
  video_id text not null references videos(id) on delete cascade,
  provider text not null,
  status text not null,
  started_at timestamptz not null default current_timestamp,
  finished_at timestamptz,
  srt_entry_count integer not null default 0,
  validation_summary text not null default '',
  fallback_reason text not null default ''
);

create table if not exists packages (
  id bigint generated by default as identity primary key,
  path text not null,
  created_at timestamptz not null default current_timestamp,
  video_count integer not null default 0,
  size_bytes bigint not null default 0,
  name text not null default '',
  locked integer not null default 0
);

create table if not exists batches (
  id text primary key,
  name text not null,
  default_content_type text not null default 'knowledge',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists workspaces (
  id text primary key,
  name text not null,
  default_workflow_key text not null default 'question_content',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  cms_config_json text not null default '{}',
  resource_config_json text not null default '{}',
  default_entity text not null default 'question',
  intake_config_json text not null default '{}',
  description text not null default ''
);

create table if not exists workspace_executor_allocations (
  workspace_id text not null references workspaces(id) on delete cascade,
  executor_id text not null,
  concurrency_limit integer not null check(concurrency_limit > 0),
  primary key(workspace_id, executor_id)
);

create table if not exists workspace_node_bindings (
  workspace_id text not null references workspaces(id) on delete cascade,
  workflow_key text not null,
  node_key text not null,
  executor_id text not null,
  primary key(workspace_id, workflow_key, node_key)
);

create table if not exists workspace_node_limits (
  workspace_id text not null references workspaces(id) on delete cascade,
  workflow_key text not null,
  node_key text not null,
  concurrency_limit integer not null check(concurrency_limit > 0),
  primary key(workspace_id, workflow_key, node_key)
);

create table if not exists job_batches (
  id text primary key,
  workspace_id text not null references workspaces(id) on delete cascade,
  workflow_key text not null,
  source_kind text not null,
  source_payload_json text not null default '{}',
  status text not null default 'created',
  created_count integer not null default 0,
  error_message text not null default '',
  created_at timestamptz not null default current_timestamp
);

create table if not exists jobs (
  id text primary key,
  workspace_id text not null references workspaces(id) on delete cascade,
  workflow_key text not null,
  source_type text not null,
  source_id text not null,
  batch_id text not null default '',
  title text not null default '',
  status text not null default 'queued',
  storage_dir text not null default '',
  error_message text not null default '',
  stem text not null default '',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  execution_mode text not null default 'full' check(execution_mode in ('full', 'until_node')),
  target_node_key text,
  execution_paused integer not null default 0 check(execution_paused in (0, 1)),
  pause_reason text not null default '',
  packed integer not null default 0,
  workflow_revision_id text not null default '',
  workflow_definition_hash text not null default '',
  workflow_definition_snapshot_json text not null default '',
  outcome text not null default '',
  workflow_version integer
);

create table if not exists job_nodes (
  id bigint generated by default as identity primary key,
  job_id text not null references jobs(id) on delete cascade,
  node_key text not null,
  status text not null default 'pending',
  stale_reason text not null default '',
  error_message text not null default '',
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default current_timestamp,
  unique(job_id, node_key)
);

create table if not exists node_runs (
  id bigint generated by default as identity primary key,
  job_id text not null references jobs(id) on delete cascade,
  node_key text not null,
  status text not null,
  started_at timestamptz not null default current_timestamp,
  finished_at timestamptz,
  command_json text not null default '[]',
  exit_code integer,
  log_path text not null default '',
  error_message text not null default '',
  run_dir text not null default '',
  session_dir text not null default '',
  skill_version text not null default '',
  runner text not null default ''
);

create table if not exists executor_leases (
  id text primary key,
  execution_id text not null unique,
  executor_id text not null,
  workspace_id text not null references workspaces(id) on delete cascade,
  job_id text not null references jobs(id) on delete cascade,
  workflow_key text not null,
  node_key text not null,
  node_run_id bigint not null references node_runs(id) on delete cascade,
  status text not null check(status in ('active', 'released', 'expired')),
  acquired_at timestamptz not null,
  heartbeat_at timestamptz not null,
  expires_at timestamptz not null
);

create table if not exists workspace_packages (
  id bigint generated by default as identity primary key,
  workspace_id text not null references workspaces(id) on delete cascade,
  path text not null,
  name text not null default '',
  job_count integer not null default 0,
  size_bytes bigint not null default 0,
  locked integer not null default 0,
  created_at timestamptz not null default current_timestamp
);

create table if not exists workflow_revisions (
  id text primary key,
  workspace_id text not null references workspaces(id) on delete cascade,
  workflow_key text not null,
  version integer not null,
  status text not null check(status in ('draft', 'active', 'archived')),
  definition_json text not null,
  definition_hash text not null,
  created_at timestamptz not null default current_timestamp,
  published_at timestamptz,
  unique(workspace_id, workflow_key, version)
);

create table if not exists node_run_token_usage (
  id bigint generated by default as identity primary key,
  node_run_id bigint not null unique references node_runs(id) on delete cascade,
  job_id text not null references jobs(id) on delete cascade,
  workspace_id text not null references workspaces(id) on delete cascade,
  node_key text not null,
  provider text not null default '',
  model text not null default '',
  skill_version text not null default '',
  message_count integer not null default 0,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  cache_read_tokens bigint not null default 0,
  total_tokens bigint not null default 0,
  usage_source text not null default 'events_jsonl',
  is_complete integer not null default 1 check(is_complete in (0, 1)),
  parse_error text not null default '',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists remote_workers (
  worker_id text primary key,
  name text not null default '',
  capabilities_json text not null,
  slots integer not null,
  registered_at timestamptz not null,
  last_seen_at timestamptz not null,
  token_hash text not null default '',
  labels_json text not null default '{}',
  revoked_at timestamptz
);

create table if not exists remote_executions (
  execution_id text primary key,
  lease_id text not null,
  job_id text not null,
  node_key text not null,
  capability text not null,
  bundle_name text not null,
  manifest_json text not null,
  state text not null default 'queued',
  worker_id text,
  requeue_count integer not null default 0,
  last_heartbeat_at timestamptz,
  outcome_json text,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  command_spec_json text
);

create table if not exists job_event_seq (
  id integer primary key check(id = 1),
  value bigint not null
);
insert into job_event_seq(id, value) values (1, 0) on conflict(id) do nothing;

create table if not exists worker_control_state (
  scope text primary key,
  paused integer not null default 1,
  updated_by text not null,
  updated_at timestamptz not null
);

create table if not exists artifacts (
  hash text primary key,
  size bigint not null,
  created_at timestamptz not null default current_timestamp
);

create table if not exists artifact_refs (
  job_id text not null references jobs(id) on delete cascade,
  node_key text not null,
  name text not null,
  hash text not null references artifacts(hash),
  primary key(job_id, node_key, name)
);

create table if not exists node_shards (
  job_id text not null references jobs(id) on delete cascade,
  node_key text not null,
  shard_index integer not null,
  status text not null default 'pending',
  input_json text not null default '{}',
  output_json text not null default '',
  error_message text not null default '',
  execution_id text not null default '',
  started_at timestamptz,
  finished_at timestamptz,
  primary key(job_id, node_key, shard_index)
);

create index if not exists idx_videos_status on videos(status);
create index if not exists idx_videos_content_type_external_id on videos(content_type, external_id);
create index if not exists idx_videos_created_at on videos(created_at);
create index if not exists idx_phase_runs_video_id on phase_runs(video_id);
create index if not exists idx_phase_runs_video_id_status on phase_runs(video_id, status);
create index if not exists idx_transcription_runs_video_id on transcription_runs(video_id);
create index if not exists idx_workspaces_created_at on workspaces(created_at);
create index if not exists idx_job_batches_workspace on job_batches(workspace_id, created_at);
alter table job_batches
  add column if not exists updated_at timestamptz not null default current_timestamp;
create index if not exists idx_job_batches_intake_queue
  on job_batches(status, updated_at) where status in ('queued', 'processing');
create index if not exists idx_jobs_workflow_status on jobs(workflow_key, status);
create index if not exists idx_jobs_workflow_source on jobs(workflow_key, source_type, source_id);
create index if not exists idx_jobs_workspace_workflow_status on jobs(workspace_id, workflow_key, status);
create index if not exists idx_jobs_workspace_workflow_source on jobs(workspace_id, workflow_key, source_type, source_id);
create index if not exists idx_job_nodes_job_status on job_nodes(job_id, status);
create index if not exists idx_node_runs_job_id on node_runs(job_id);
create index if not exists idx_node_runs_status_finished_at on node_runs(status, finished_at);
create index if not exists idx_jobs_status on jobs(status);
create index if not exists idx_executor_leases_global_active on executor_leases(executor_id, status, expires_at);
create index if not exists idx_executor_leases_workspace_active on executor_leases(workspace_id, executor_id, status, expires_at);
create index if not exists idx_executor_leases_workflow_node_active on executor_leases(workspace_id, workflow_key, node_key, status, expires_at);
create index if not exists idx_executor_leases_status_expires_at on executor_leases(status, expires_at);
create index if not exists idx_executor_leases_job_status on executor_leases(job_id, status);
create index if not exists idx_workspace_packages_workspace_id on workspace_packages(workspace_id, created_at desc);
create index if not exists idx_workflow_revisions_active on workflow_revisions(workspace_id, workflow_key, status);
create index if not exists idx_node_run_token_usage_workspace on node_run_token_usage(workspace_id, node_key);
create index if not exists idx_node_run_token_usage_model on node_run_token_usage(provider, model);
create index if not exists idx_node_run_token_usage_skill_version on node_run_token_usage(skill_version);
create index if not exists idx_node_runs_run_dir on node_runs(run_dir);
create index if not exists idx_node_run_token_usage_job_id on node_run_token_usage(job_id);
create index if not exists idx_remote_executions_dequeue on remote_executions(capability, created_at, execution_id) where state = 'queued';
create index if not exists idx_artifact_refs_hash on artifact_refs(hash);
