# ruff: noqa: F403, F405
from server.app.db.migrations._migration_imports import *
from server.app.db.migrations.models import Migration

MIGRATIONS: tuple[Migration, ...] = (
    V001_EXECUTOR_CORE,
    V002_EXECUTOR_BOOTSTRAP_STATE,
    V003_LEGACY_COLUMNS,
    V004_WORKSPACE_DAG_FOREIGN_KEYS,
    V006_JOB_EXECUTION_CONTROL,
    V007_RENAME_PIPELINE_TO_WORKFLOW,
    V008_JOB_NODE_CREATED_AT,
    V009_RELATIVE_PATH_STORAGE,
    V010_REMOVE_DEFAULT_WORKSPACE,
    V011_REMOVE_WORKSPACE_ID_DEFAULTS,
    V012_WORKSPACE_PACKAGES,
    V013_NODE_RUN_SKILL_VERSION,
    V014_REMOVE_QUESTION_CONTENT_DEFAULT,
    V015_RENAME_PI_EXECUTOR_ID,
    V016_WORKFLOW_REVISIONS,
    V017_JOB_WORKFLOW_VERSION,
    V018_NODE_RUN_TOKEN_USAGE,
    V019_REMOTE_WORKERS,
    V020_NODE_RUN_RUNNER,
    V021_REMOTE_EXECUTIONS,
    V022_JOB_EVENT_SEQ_WORKER_CONTROL,
)
